add_newline = false

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[➜](bold green)"
#error_symbol = "[✗](bold red)"

#[cmd_duration]
#format = "took [$duration](bold purple)"

[line_break]
disabled = true

[package]
disabled = true

[battery]
disabled = true
